name: Build Cydia Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dpkg-dev and build tools
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev bzip2

      - name: Package existing build files
        run: |
          mkdir -p build_stage/DEBIAN
          mkdir -p build_stage/Applications
          
          cp "My First App/control" build_stage/DEBIAN/control
          
          dpkg-deb --build build_stage my-first-app.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cydia-package
          path: my-first-app.deb
