name: Build Cydia Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Theos and dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y dpkg-dev bzip2 make git clang ldid
          git clone --recursive https://github.com/theos/theos.git ~/theos

      - name: Build package with Theos
        run: |
          export THEOS=~/theos
          cd "My First App"
          make package
